[build]
  base = "."
  publish = "frontend/dist"
  command = "npm install && cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# API routes - redirect to Netlify Functions
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# Handle static assets first
[[redirects]]
  from = "/logo.jpg"
  to = "/logo.jpg"
  status = 200
  force = true

[[redirects]]
  from = "/ShakshamKarkiResume.pdf"
  to = "/ShakshamKarkiResume.pdf"
  status = 200
  force = true

# Redirect all other requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
